### ISSUE TITLE
Calling sleep() is causing an error of "Unable to load spec files"

### ISSUE THREAD

**Issue by jeffb-sfdc** [webdriverio-community/wdio-vscode-service#63] opened 2023-01-24 00:05 UTC
I'm attempting to upgrade our project from wdio-vscode-service 4.1.0 to 5.0.0.  I've encountered a few issues (more on that later), but I've encountered (what I think is) an "out of the box" error, which code which contains calls to `sleep()` is causing an error of
```
Error:  Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
`browser` object has only `capabilities` and some flags like `isMobile`.
Helper files that use other `browser` commands have to be moved to `before` hook.
Spec file(s): file:///my-username/temp/new-wdio-test/test/specs/example.e2e.ts
Error: Error: Cannot find module '/my-username/temp/new-wdio-test/node_modules/wdio-vscode-service/dist/cjs/index.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:960:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:953:15)
    at resolveExports (node:internal/modules/cjs/loader:482:14)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/my-username/temp/new-wdio-test/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/my-username/temp/new-wdio-test/test/specs/example.e2e.ts:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module.m._compile (/my-username/temp/new-wdio-test/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Object.require.extensions.<computed> [as .ts] (/my-username/temp/new-wdio-test/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[0-0] FAILED in chrome - file:///test/specs/example.e2e.ts
```

It's hard to tell from this error... the error being reported says the browser object isn't being initialized,
but it's also saying that it can't find `node_modules/wdio-vscode-service/dist/cjs/index.js`, and I can confirm that `node_modules/wdio-vscode-servicedist/cjs` doesn't exist.

### Steps to reproduce:
1. Follow the installation and configuration steps listed at https://github.com/webdriverio-community/wdio-vscode-service/tree/main/test
(note, there are some steps in this README that are stale and need to be updated - I'll probably create a PR with updated steps later)
2. Modify `/test/specs/example.e2e.ts` to:
```
import LoginPage from '../pageobjects/login.page'
import SecurePage from '../pageobjects/secure.page'

import {
    sleep
} from 'wdio-vscode-service';

describe('My Login application', () => {
    it('should login with valid credentials', async () => {
        /*
        await LoginPage.open()

        await LoginPage.login('tomsmith', 'SuperSecretPassword!')
        await expect(SecurePage.flashAlert).toBeExisting()
        await expect(SecurePage.flashAlert).toHaveTextContaining(
            'You logged into a secure area!')
        */
        sleep(1000);
        expect(1).toBe(1);
    })
})
```

3. go back to the terminal and run `npm run wdio`

Results:
* You get the error I mentioned above.
* If you comment out the call to `sleep()` (but still import it) an run the test again, the test passes.

If needed, I can zip up the project and attach it to this ticket.

**Comment by christian-bromann** [comment] 2023-01-24 05:35
@jeffb-sfdc thanks for reporting the issue. The error you are seeing is because `v5.0.0` stopped supporting CJS. I am looking into providing support for it but it is not quite straight forward. For the projects we use we run all WDIO tests with ESM.

**Comment by jeffb-sfdc** [comment] 2023-01-24 16:41
Is the issue then with the `tsconfig.json` that was generated?  I found that I needed to change `module` in `tsconfig.json` in order to get it to run.  Following the instructions, what was generated was:
```
{
    "compilerOptions": {
        "moduleResolution": "node",
        "module": "ESNext",
        "types": [
            "node",
            "@wdio/globals/types",
            "expect-webdriverio",
            "@wdio/mocha-framework",
        ],
        "target": "es2022",
        "esModuleInterop": true
    }
}
```
...and then I also added `wdio-vscode-service`:
```
{
    "compilerOptions": {
        "moduleResolution": "node",
        "module": "ESNext",
        "types": [
            "node",
            "@wdio/globals/types",
            "expect-webdriverio",
            "@wdio/mocha-framework",
            "wdio-vscode-service"
        ],
        "target": "es2022",
        "esModuleInterop": true
    }
}
```

...but when this runs, I get an error of:
```
ERROR @wdio/config:ConfigParser: Failed loading configuration file: file:///my-user/temp/new-wdio-test-take-two/wdio.conf.ts: Unexpected token 'export'
/my-user/temp/new-wdio-test-take-two/wdio.conf.ts:1
export const config = {
^^^^^^

SyntaxError: Unexpected token 'export'
.
.
.
```

I tried most of the different module values, and the only value that worked (to the point where WDIO would start), was a module value of `CommonJS`, but then I get the error I reported above.

**Comment by christian-bromann** [comment] 2023-04-26 22:39
@jeffb-sfdc did you find a solution to this? A reproducible example would help to support you here. I am sure it is a TS setup problem that is fixable.

**Comment by jeffb-sfdc** [comment] 2023-05-26 14:46
@christian-bromann , no we don't have a fix.  We are stuck at v4.2.1 and not able to use v5.x

**Comment by christian-bromann** [comment] 2023-05-26 15:38
Unfortunately I currently don't have time and resources to provide a CJS export for this package which is required because you have to import its page objects from it. I would recommend going forward to rewrite the tests into ESM and keep your extension files in CJS.

**Comment by christian-bromann** [comment] 2023-07-08 01:30
I will go ahead and close this. I personally don't have much interest working on providing a CJS export to make it compatible with WebdriverIO v7. I rather use the time help you upgrade to v8. Let me know if there is anything I can do.

**Closed by christian-bromann** 2023-07-08 01:30 UTC
Labels: help wanted
