### ISSUE TITLE
Last version of test runner is broken

### ISSUE THREAD

**Issue by degrammer** [webdriverio-community/wdio-vscode-service#88] opened 2023-11-08 05:45 UTC
It seems the latest version of the test runner is broken, this is due a dependency from vscode-uri that introduced some changes that IMO are breaking and are not properly handled in latest version.

This error is coming from a fresh install of using the command `npm create wdio@latest ./`

<img width="1487" alt="Screenshot 2023-11-08 at 12 44 04 AM" src="https://github.com/webdriverio-community/wdio-vscode-service/assets/145692208/e1c3fa57-6ebb-4b23-9379-182ca1a589cc">

**Comment by me-rsharma** [comment] 2023-11-08 06:03
@degrammer I have the same when trying to run test of wdio-vscode-service `Execution of 1 workers started at 2023-11-08T06:00:15.750Z

2023-11-08T06:00:15.832Z DEBUG @wdio/utils:initialiseServices: initialise service "vscode" as NPM package
2023-11-08T06:00:17.522Z INFO @wdio/local-runner: Shutting down spawned worker
2023-11-08T06:00:17.789Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-11-08T06:00:17.790Z INFO @wdio/local-runner: shutting down
Error: Error: Failed to initilialise launcher service unknown: Error: Couldn't initialise "wdio-vscode-service".
TypeError: Cannot destructure property 'URI' of '(intermediate value).default' as it is undefined.
    at file:///C:/Users/rajeshwar.sharma/Cerence/studio/wdio-vscode-service/node_modules/wdio-vscode-service/src/server/utils.ts:6:9      
    at safeImport (file:///C:/Users/rajeshwar.sharma/Cerence/studio/wdio-vscode-service/node_modules/@wdio/utils/build/utils.js:223:15)   
    at async initialisePlugin (file:///C:/Users/rajeshwar.sharma/Cerence/studio/wdio-vscode-service/node_modules/@wdio/utils/build/initialisePlugin.js:31:20)`

**Comment by tzAcee** [comment] 2023-11-12 17:37
related: #81

**Comment by mikhail-g** [comment] 2023-11-15 18:46
the issue is in src/server/utils.ts:6:45
`const { URI } = (await import('vscode-uri')).default`
if you remove `.default` it will work

**Comment by christian-bromann** [comment] 2023-11-28 07:20
A fix for this bug is merged and will be released momentarily.

**Closed by christian-bromann** 2023-11-28 07:20 UTC
